import type { ImageSourcePropType } from 'react-native';

import type { TKanda } from '@/types/content';

export type CharacterRole = 'hero' | 'ally' | 'sage' | 'monarch' | 'antagonist';

export type CharacterMeta = {
  id: string;
  name: string;
  epithet: string;
  role: CharacterRole;
  summary: string;
  bio: string;
  traits: string[];
  kanda: TKanda;
  startSarga: string;
  image: ImageSourcePropType;
};

export const CHARACTERS: CharacterMeta[] = [
  {
    id: 'rama',
    name: 'Rama',
    epithet: 'Prince of Ayodhya',
    role: 'hero',
    summary: 'The ideal king — dharma made visible in human form.',
    bio: 'Seventh avatar of Vishnu and eldest son of Dasharatha. Rama embodies righteousness, restraint, and compassion through exile, war, and rule. His journey from Ayodhya to the forest and back defines the moral spine of the epic.',
    traits: ['Dharma', 'Patience', 'Leadership'],
    kanda: 'bala',
    startSarga: '1',
    image: require('../../assets/characters/rama.png'),
  },
  {
    id: 'sita',
    name: 'Sita',
    epithet: 'Daughter of the Earth',
    role: 'hero',
    summary: 'Incarnation of Lakshmi; steadfast through trial and exile.',
    bio: 'Born from the earth and raised in Mithila, Sita chooses Rama as her husband and follows him into exile. Her abduction by Ravana sets the great war in motion; her fidelity and courage remain central to the story.',
    traits: ['Devotion', 'Fortitude', 'Grace'],
    kanda: 'bala',
    startSarga: '73',
    image: require('../../assets/characters/sita.png'),
  },
  {
    id: 'lakshmana',
    name: 'Lakshmana',
    epithet: 'The Ever-Watchful Brother',
    role: 'ally',
    summary: 'Rama\'s devoted brother and guardian in exile.',
    bio: 'Son of Sumitra and inseparable companion to Rama. Lakshmana accompanies the exile, protects Sita, and stands as the model of loyal service — sleepless, swift to act, and fierce in battle.',
    traits: ['Loyalty', 'Vigilance', 'Courage'],
    kanda: 'ayodhya',
    startSarga: '31',
    image: require('../../assets/characters/lakshmana.png'),
  },
  {
    id: 'hanuman',
    name: 'Hanuman',
    epithet: 'Son of the Wind',
    role: 'ally',
    summary: 'The devoted vanara who leaps oceans for dharma.',
    bio: 'Minister to Sugriva and supreme devotee of Rama. Hanuman\'s journey to Lanka, meeting with Sita, and burning of the city make Sundara Kanda the emotional heart of the epic for many readers.',
    traits: ['Bhakti', 'Strength', 'Wisdom'],
    kanda: 'kishkindha',
    startSarga: '1',
    image: require('../../assets/characters/hanuman.png'),
  },
  {
    id: 'ravana',
    name: 'Ravana',
    epithet: 'Lord of Lanka',
    role: 'antagonist',
    summary: 'A scholar-king undone by pride and desire.',
    bio: 'Ten-headed ruler of Lanka, master of the Vedas, and brother of Kubera. Ravana\'s power is immense, yet his abduction of Sita brings about his downfall — a study in brilliance without restraint.',
    traits: ['Power', 'Pride', 'Scholarship'],
    kanda: 'aranya',
    startSarga: '31',
    image: require('../../assets/characters/ravana.png'),
  },
  {
    id: 'dasharatha',
    name: 'Dasharatha',
    epithet: 'Emperor of Kosala',
    role: 'monarch',
    summary: 'The father whose promise shapes the exile.',
    bio: 'King of Ayodhya and father of Rama. Dasharatha\'s boons to Kaikeyi and his anguish at sending Rama to the forest open Ayodhya Kanda — a portrait of duty colliding with love.',
    traits: ['Honor', 'Grief', 'Kingship'],
    kanda: 'bala',
    startSarga: '8',
    image: require('../../assets/characters/dasharatha.png'),
  },
  {
    id: 'sugriva',
    name: 'Sugriva',
    epithet: 'King of Kishkindha',
    role: 'ally',
    summary: 'Exiled vanara king who allies with Rama.',
    bio: 'Brother of Vali and ruler of the monkey kingdom. Rama helps Sugriva regain his throne; in return Sugriva mobilizes the search for Sita across land and sea.',
    traits: ['Alliance', 'Recovery', 'Rule'],
    kanda: 'kishkindha',
    startSarga: '1',
    image: require('../../assets/characters/sugriva.png'),
  },
  {
    id: 'valmiki',
    name: 'Valmiki',
    epithet: 'The First Poet',
    role: 'sage',
    summary: 'Hermit-sage who receives and records the epic.',
    bio: 'Adi Kavi — the first poet. Narada instructs Valmiki to compose the Ramayana; the epic unfolds through his vision, making him both witness and author of the story we read.',
    traits: ['Vision', 'Sanskrit', 'Transmission'],
    kanda: 'bala',
    startSarga: '1',
    image: require('../../assets/characters/valmiki.png'),
  },
  {
    id: 'bharata',
    name: 'Bharata',
    epithet: 'He Who Refused the Throne',
    role: 'ally',
    summary: 'Rama\'s brother who rules Ayodhya only in his name.',
    bio: 'Son of Kaikeyi and younger brother of Rama. Returning to a grief-stricken Ayodhya after Dasharatha\'s death, Bharata rejects the crown, reproaches the exile, and vows to bring Rama home — ruling only as keeper of Rama\'s sandals until the true king returns.',
    traits: ['Renunciation', 'Duty', 'Devotion'],
    kanda: 'ayodhya',
    startSarga: '71',
    image: require('../../assets/characters/bharata.png'),
  },
  {
    id: 'kaikeyi',
    name: 'Kaikeyi',
    epithet: 'Queen of the Two Boons',
    role: 'antagonist',
    summary: 'The queen whose demands send Rama into exile.',
    bio: 'Youngest queen of Dasharatha and mother of Bharata. Persuaded by Manthara, she enters the house of wrath and claims the boons once granted her — Bharata\'s coronation and Rama\'s fourteen-year exile — setting Ayodhya Kanda in motion.',
    traits: ['Ambition', 'Resolve', 'Consequence'],
    kanda: 'ayodhya',
    startSarga: '10',
    image: require('../../assets/characters/kaikeyi.png'),
  },
  {
    id: 'shatrughna',
    name: 'Shatrughna',
    epithet: 'Destroyer of Foes',
    role: 'ally',
    summary: 'Bharata\'s twin in loyalty and Rama\'s steadfast brother.',
    bio: 'Son of Sumitra and devoted companion to Bharata. He grieves with his brother at Dasharatha\'s death, seizes Manthara in anger, and stands beside Bharata through the painful work of restoring Rama to his rightful place.',
    traits: ['Loyalty', 'Zeal', 'Brotherhood'],
    kanda: 'ayodhya',
    startSarga: '78',
    image: require('../../assets/characters/shatrughna.png'),
  },
  {
    id: 'vibhishana',
    name: 'Vibhishana',
    epithet: 'Righteous Brother of Ravana',
    role: 'ally',
    summary: 'The rakshasa who chose dharma over kin.',
    bio: 'Younger brother of Ravana and a voice of morality in Lanka. He urges Ravana to restore Sita to Rama, is scorned for his counsel, and seeks refuge at Rama\'s feet — joining the war as a righteous ally and later receiving the kingdom of Lanka.',
    traits: ['Dharma', 'Courage', 'Surrender'],
    kanda: 'yuddha',
    startSarga: '9',
    image: require('../../assets/characters/vibhishana.png'),
  },
  {
    id: 'indrajit',
    name: 'Indrajit',
    epithet: 'Conqueror of Indra',
    role: 'antagonist',
    summary: 'Ravana\'s son whose sorcery nearly breaks the war.',
    bio: 'Also called Meghanada, foremost warrior among Ravana\'s sons. He masters illusions in battle, wounds Rama and Lakshmana, and stands as Lanka\'s deadliest defender until Lakshmana meets him in the decisive duel of Yuddha Kanda.',
    traits: ['Sorcery', 'Prowess', 'Pride'],
    kanda: 'yuddha',
    startSarga: '15',
    image: require('../../assets/characters/indrajit.png'),
  },
  {
    id: 'jatayu',
    name: 'Jatayu',
    epithet: 'King of the Vultures',
    role: 'ally',
    summary: 'The aged eagle who gave his life for Sita.',
    bio: 'Mighty vulture-king and friend of Dasharatha. Meeting Rama in exile, he offers his aid; when Ravana carries Sita away, Jatayu rises to stop him and falls mortally wounded — his death revealing the path of the abduction.',
    traits: ['Sacrifice', 'Valour', 'Friendship'],
    kanda: 'aranya',
    startSarga: '14',
    image: require('../../assets/characters/jatayu.png'),
  },
  {
    id: 'surpanakha',
    name: 'Surpanakha',
    epithet: 'She Who Shaped the War',
    role: 'antagonist',
    summary: 'Ravana\'s sister whose wound summons Lanka\'s wrath.',
    bio: 'Rakshasi sister of Ravana, Khara, and Dushana. Her advances toward Rama in Panchavati are rebuffed; when Lakshmana punishes her, she flees to her kin and sets in motion the demon armies — and Ravana\'s resolve to abduct Sita.',
    traits: ['Pride', 'Vengeance', 'Fate'],
    kanda: 'aranya',
    startSarga: '17',
    image: require('../../assets/characters/surpanakha.png'),
  },
  {
    id: 'kumbhakarna',
    name: 'Kumbhakarna',
    epithet: 'The Sleeping Giant',
    role: 'antagonist',
    summary: 'Ravana\'s colossal brother, roused for a last stand.',
    bio: 'Enormous brother of Ravana, cursed to sleep for long ages yet unrivalled in battle when awake. Ravana rouses him as Lanka falters; Kumbhakarna counsels return of Sita, then marches out and falls fighting Rama\'s forces.',
    traits: ['Strength', 'Sleep', 'Fury'],
    kanda: 'yuddha',
    startSarga: '62',
    image: require('../../assets/characters/kumbhakarna.png'),
  },
  {
    id: 'mandodari',
    name: 'Mandodari',
    epithet: 'Queen of Lanka',
    role: 'monarch',
    summary: 'Ravana\'s chief queen — wisdom beside power.',
    bio: 'Beloved chief consort of Ravana and mother of Meghanada. Hanuman first glimpses her in the palace of Lanka; she restrains Ravana\'s wrath toward Sita at times, and after his fall she laments with clear sight of dharma violated and its cost.',
    traits: ['Dignity', 'Insight', 'Grief'],
    kanda: 'sundara',
    startSarga: '10',
    image: require('../../assets/characters/mandodari.png'),
  },
  {
    id: 'vishvamitra',
    name: 'Vishvamitra',
    epithet: 'Sage of the Sacred Missiles',
    role: 'sage',
    summary: 'The ascetic who takes Rama into the world of duty.',
    bio: 'Former king turned brahmarishi, famed for his tapas and rivalry with Vasishtha. He arrives at Ayodhya to take Rama and Lakshmana to guard his sacrifice, teaches them the divine missiles, and guides their early trials in Bala Kanda.',
    traits: ['Tapas', 'Guidance', 'Power'],
    kanda: 'bala',
    startSarga: '19',
    image: require('../../assets/characters/vishvamitra.png'),
  },
  {
    id: 'kausalya',
    name: 'Kausalya',
    epithet: 'Mother of the Prince',
    role: 'monarch',
    summary: 'Rama\'s mother — dignity in joy and in grief.',
    bio: 'Chief queen of Dasharatha and mother of Rama. She rejoices at his prospective coronation, then endures the sharpest grief when exile is decreed — blessing Rama to go, rebuking injustice, and embodying a mother\'s love bound to dharma.',
    traits: ['Maternity', 'Fortitude', 'Grace'],
    kanda: 'ayodhya',
    startSarga: '20',
    image: require('../../assets/characters/kausalya.png'),
  },
  {
    id: 'vali',
    name: 'Vali',
    epithet: 'King of Kishkindha',
    role: 'antagonist',
    summary: 'The vanara lord whose feud shapes the search for Sita.',
    bio: 'Mighty king of the monkeys and elder brother of Sugriva. Doubt and rivalry drive him to banish Sugriva and keep his wife; Rama, bound by alliance, confronts Vali in combat — a turning point that sets the monkey hosts marching toward Lanka.',
    traits: ['Sovereignty', 'Wrath', 'Tragedy'],
    kanda: 'kishkindha',
    startSarga: '8',
    image: require('../../assets/characters/vali.png'),
  },
  {
    id: 'angada',
    name: 'Angada',
    epithet: 'Vali\'s Son, Rama\'s Envoy',
    role: 'ally',
    summary: 'Young prince of the vanaras who carries the mission forward.',
    bio: 'Son of Vali and Tara, nephew to Sugriva. When the search for Sita grows desperate, Angada rallies the monkey hosts, leads them south, and stands at the heart of their perilous quest — a prince learning duty in the service of Rama.',
    traits: ['Youth', 'Leadership', 'Resolve'],
    kanda: 'kishkindha',
    startSarga: '49',
    image: require('../../assets/characters/angada.png'),
  },
  {
    id: 'shabari',
    name: 'Shabari',
    epithet: 'The Forest Devotee',
    role: 'sage',
    summary: 'The ascetic whose hospitality blesses Rama\'s exile.',
    bio: 'Elderly tribal devotee dwelling by the Pampa lake, awaiting Rama as her guru had foretold. She welcomes the princes with humble offerings and receives moksha at their feet — a brief meeting that illumines the path of selfless devotion.',
    traits: ['Bhakti', 'Humility', 'Liberation'],
    kanda: 'aranya',
    startSarga: '74',
    image: require('../../assets/characters/shabari.png'),
  },
];

export function getCharacter(id: string): CharacterMeta | undefined {
  return CHARACTERS.find((c) => c.id === id);
}

export const ROLE_LABELS: Record<CharacterRole, string> = {
  hero: 'Hero',
  ally: 'Ally',
  sage: 'Sage',
  monarch: 'Monarch',
  antagonist: 'Antagonist',
};
